front:
    # Official docker image.
    image: docker:stable
    stage: build
    services:
        - docker:dind
    variables:
        IMAGE_TAG: $CI_REGISTRY_IMAGE:front
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    script:
        - echo $VUE_APP_URL
        - docker build --build-arg VUE_APP_URL=$VUE_APP_URL --build-arg VUE_APP_STRIPE_PK=$VUE_APP_STRIPE_PK --pull --network host -t $IMAGE_TAG .
        - docker push $IMAGE_TAG
    only:
        refs:
            - develop

front-prod:
    # Official docker image.
    image: docker:stable
    stage: build
    services:
        - docker:dind
    variables:
        IMAGE_TAG: $CI_REGISTRY_IMAGE:front-prod
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    script:
        - echo $VUE_APP_URL_PROD
        - docker build --build-arg VUE_APP_URL=$VUE_APP_URL_PROD --build-arg VUE_APP_STRIPE_PK=$VUE_APP_STRIPE_PK_PROD --pull --network host -t $IMAGE_TAG .
        - docker push $IMAGE_TAG
    only:
        refs:
            - master
