export const GET_BASIC_ANALYTICS_BY_AUTH_USER = 'GET_BASIC_ANALYTICS_BY_AUTH_USER';
export const GET_ADVANCED_ANALYTICS_BY_AUTH_USER = 'GET_ADVANCED_ANALYTICS_BY_AUTH_USER';
export const GET_ADVANCED_ANALYTICS_LOG = 'GET_ADVANCED_ANALYTICS_LOG';
export const SAVE_ACTION = 'SAVE_ACTION';
export const SET_DEVICE_ID = 'SET_DEVICE_ID';
