export const ADD_CONTENT_TO_CARD = 'ADD_CONTENT_TO_CARD';
export const SET_CONTENT = 'SET_CONTENT';
export const GET_CONTENT = 'GET_CONTENT';
export const UPDATE_CONTENT = 'UPDATE_CONTENT';
export const DELETE_CONTENT = 'DELETE_CONTENT';
export const REMOVE_DELETED_CONTENT = 'REMOVE_DELETED_CONTENT';
export const REORDER_CONTENT_SECTION = 'REORDER_CONTENT_SECTION';
