export const GET_PRODUCTS_AND_PLANS = 'GET_PRODUCTS_AND_PLANS';
export const SET_PRODUCTS_AND_PLANS = 'SET_PRODUCTS_AND_PLANS';
export const SUBSCRIBE_TO_PLAN = 'SUBSCRIBE_TO_PLAN';
export const UNSUBSCRIBE_TO_PLAN = 'UNSUBSCRIBE_TO_PLAN';
export const RENEW_PLAN_SUBSCIPTION = 'RENEW_PLAN_SUBSCIPTION';
