export const GENERATE_XLSX_FILE = 'GENERATE_XLSX_FILE';
export const CREATE_TAG = 'CREATE_TAG';
export const UPDATE_TAG = 'UPDATE_TAG';
export const GET_TAGS_LIST = 'GET_TAGS_LIST';
export const BIND_TAG_TO_CARD = 'BIND_TAG_TO_CARD';
export const BIND_TAG_FOR_AUTHENTICATED_USER = 'BIND_TAG_FOR_AUTHENTICATED_USER';
