export const GET_AUTH_USER_INFO = 'GET_AUTH_USER_INFO';
export const SET_AUTH_USER_INFO = 'SET_AUTH_USER_INFO';
export const SET_PRIMARY_CARD_ID = 'SET_PRIMARY_CARD_ID';
export const GET_DOWNLOADS_TOKEN = 'GET_DOWNLOADS_TOKEN';
